#!/bin/sh

printf "\n"
printf "  +---------------------------------------+\n"
printf "  |       Pre-Commit Code Review           |\n"
printf "  +---------------------------------------+\n"
printf "\n"

cmd.exe /c "./run-reviewer.bat"
status=$?

if [ $status -ne 0 ]; then
  printf "\n"
  printf "  Commit blocked. Fix [!!] issues first.\n"
  printf "\n"
fi

exit $status
